#!/bin/bash

mountpoint /sys/firmware/efi/efivars || mount -v -t efivarfs efivarfs /sys/firmware/efi/efivars

echo "GRUB_ENABLE_CRYPTODISK=y" > /etc/default/grub

grub-install --bootloader-id=SWL --recheck

umount /sys/firmware/efi/efivars
