#!/bin/bash

####################################################################
# QT5 COMPONENTS

export QT5PREFIX=/opt/qt5

cat >> /etc/ld.so.conf << EOF
# Begin Qt addition

/opt/qt5/lib

# End Qt addition
EOF

ldconfig


####################################################################
# QT6

export QT6PREFIX=/opt/qt6

cat >> /etc/ld.so.conf << EOF
# Begin Qt addition

/opt/qt6/lib

# End Qt addition
EOF

ldconfig

