####################################################################
#
#
#
####################################################################

blfs_build = /usr/src/slackwiig-lfs/scripts/build-blfs
swl_ice_blfs = /usr/src/slackwiig-lfs/scripts/swlBuild/swl-ice/swl-ice.blfs

### BUILD BLFS DEPS ###
all : 
	$(blfs_build) $(swl_ice_blfs)
