#!/bin/bash
###################################################################
#
# swl-install
#
# Install lfs-base and swl-base packages
#
###################################################################

source /usr/sbin/swlm-config


###################################################################
# USAGE
###################################################################
function usage
{
        cat << EOF

swl-manager browse
swl-manager install
swl-manager list

EOF
}


case $1 in

	browse) lynx $SWL_MIRROR ;;

	install) $SWL_INSTALL $2 $3 ;;

	list) $SWL_LIST $2 $3 ;;

	*) usage ;;

esac
