#!/bin/bash
###################################################################
#
# swl-install
#
# Install lfs-base and swl-base packages
#
###################################################################

source /usr/sbin/swlm-config


###################################################################
# USAGE
###################################################################
function usage
{
        cat << EOF

swl-manager audit
swl-manager browse
swl-manager install
swl-manager list
swl-manager upgrade

EOF
}


case $1 in

	audit) $SWL_AUDIT $2 ;;

	browse) lynx $SWL_MIRROR ;;

	install) $SWL_INSTALL $2 $3 ;;

	list) $SWL_LIST $2 $3 ;;

	upgrade) $SWL_UPGRADE $2 ;;

	*) usage ;;

esac
