#!/bin/bash


export SWL_DIR_PATH=$ROOT/var/lib/swl
export SWL_VERSION_FILE=$SWL_DIR_PATH/swl-version
if [[ -f $SWL_VERSION_FILE ]]; then export SWL_VERSION=$(cat $SWL_VERSION_FILE);
else export SWL_VERSION=${SWL_VERSION:-NOVERSION}; fi


export SWL_PKG_VERSIONS_FILE=$SWL_DIR_PATH/pkg-versions-$SWL_VERSION.jhalfs
export SWL_PKG_DIR_PATH=$SWL_DIR_PATH/packages
export SWL_SBIN_PATH=$ROOT/usr/sbin

# chroot path
export SWL_POLKIT_INIT=/usr/src/slackwiig-lfs/scripts/init/polkit-init


export SWL_BLFS_SCRIPT_PATH=$HOME/blfs_root/scripts


export SWL_MIRROR=http://swl-mirror:8000
export SWL_MIRROR_VERSIONS_PATH=${SWL_MIRROR}/swl
export SWL_MIRROR_PACKAGES_PATH=$SWL_MIRROR_VERSIONS_PATH/$SWL_VERSION/packages
export SWL_LFSBASE_LIST_URL=$SWL_MIRROR_VERSIONS_PATH/$SWL_VERSION/lists/lfs-base.list
export SWL_SWLBASE_LIST_URL=$SWL_MIRROR_VERSIONS_PATH/$SWL_VERSION/lists/swl-base.list


export SWL_INSTALL_CMD="installpkg --terse"
export SWL_REMOVE_CMD="removepkg --terse"



export SWL_BASE_DIR=$ROOT/var/lib/swl
export SWL_LIST_DIR=$SWL_BASE_DIR/lists


export SWL_INSTALL_PATH=/usr/src/slackwiig-lfs
export SWL_INSTALL=$SWL_INSTALL_PATH/swl-manager/swlm-install
export SWL_LIST=$SWL_INSTALL_PATH/swl-manager/swlm-list
export SWL_AUDIT=$SWL_INSTALL_PATH/swl-manager/swlm-audit


export SWL_PKG_INSTALL_DIR=$ROOT/var/lib/pkgtools/packages

