#!/bin/bash
###################################################################
#
# swl-install
#
# Install lfs-base and swl-base packages
#
###################################################################

source $SWL_INSTALL_PATH/api/swl-api-functions


###################################################################
# USAGE
###################################################################
function usage
{
	cat << EOF

INSTALL USAGE:

ROOT=/install/root swl-manager install (options) <version>

OPTIONS:
	-l	lfs-base only
	-v	display mirror available versions
	-c	configure installation (passwd, fstab)

EOF
}


####################################################################
# CONFIGURATION
####################################################################

#------------------------------------------------------------------#
# Parse command line
#------------------------------------------------------------------#

if [[ -z $1 ]]; then usage; exit; fi

version=0
swlbase=true
configure=false

case $1 in

	-v) 	;;
	-l)	if [[ -z $2 ]]; then usage; exit; fi
		version=$2
		swlbase=false
		;;
		
	-c) 	configure=true ;;
	*) 	version=$1 ;;
esac


#------------------------------------------------------------------#
# CONFIGURE ONLY
#------------------------------------------------------------------#

if [[ $configure == true ]]; then install_configure; exit 0; fi


#------------------------------------------------------------------#
# GET MIRROR VERSIONS
#------------------------------------------------------------------#

mirror_versions=$(mirror_get_versions)

if [[ $version == 0 ]]; then

	echo
	echo "Versions available on mirror $SWL_MIRROR:"
	echo

	for each in $mirror_versions
	do
		echo $each
	done

	exit
fi

### Verify mirror ###
if [[ ! "$mirror_versions" =~ (^|[ ])$version([ ]|$) ]]; then
	echo ""
	echo "ERROR: Version $version not found on mirror $SWL_MIRROR"
	echo ""
	echo "Available versions: $mirror_versions"
	exit
fi

#------------------------------------------------------------------#
# Summary output and user verification
#------------------------------------------------------------------#

# Install root
install_root="/"
if [[ ! -z $ROOT ]]; then install_root=$ROOT; fi

echo ""
echo "Installation Summary:"
echo ""
echo "VERSION: $version"
echo "INSTALL ROOT: $install_root"
echo "SWL BASE: $swlbase"
echo ""
echo "WARNING! Data on $install_root could be permanently modified and render the system unusable!"
echo ""
read -p "Is this configuration acceptable? (Yes): " confirm 
if [[ $confirm != "Yes" ]]; then echo "Cancelling..."; exit 1; fi


####################################################################
# DOWNLOAD PACKAGES
####################################################################

### Create temp dir on install root for package download ###
tmpdir="${ROOT}/swltmpdir$RANDOM"

set -e # exit on error

### Download lfs-base packages ###
echo ""
echo "Downloading lfs base packages..."
echo ""

lfsbasedir=$tmpdir/lfs-base
mkdir -pv $lfsbasedir

url=$SWL_MIRROR_VERSIONS_PATH/$version/base/lfs/
wget -r -np -nd -P $lfsbasedir $url


### Download swl-base packages ###
if [[ $swlbase == true ]]; then
	echo ""
	echo "Downloading swl base packages..."
	echo ""

	swlbasedir=$tmpdir/swl-base
	mkdir -pv $swlbasedir

	url=$SWL_MIRROR_VERSIONS_PATH/$version/base/swl/
	wget -r -np -nd -P $swlbasedir $url
fi

set -e


####################################################################
# INSTALL PACKAGES
####################################################################

### Install lfs base ###
echo ""
echo "Installing lfs base packages..."
echo ""

$SWL_INSTALL_CMD $lfsbasedir/*.txz

### Install swl base ###
if [[ $swlbase == true ]]; then
	echo ""
	echo "Installing swl base packages..."
	echo ""

	$SWL_INSTALL_CMD $swlbasedir/*.txz

	# create lfs base list
	ls $lfsbasedir > $SWL_LIST_DIR/lfs-base.list

	# create swl base list
	ls $swlbasedir > $SWL_LIST_DIR/swl-base.list
fi


####################################################################
# INITIALIZE INSTALLATION
####################################################################

# passwd and fstab
install_configure


### Initialize swl ###
if [[ $swlbase == true ]]; then

	# Install swl
	echo
        echo "Installing swl..."
        echo
        git clone https://github.com/wiigelec/slackwiig-lfs $ROOT/$SWL_INSTALL_PATH
        echo

	# Create links
	ln -sv /usr/src/slackwiig-lfs/swl-manager/swl-manager $SWL_SBIN_PATH
	ln -sv /usr/src/slackwiig-lfs/swl-manager/swlm-config $SWL_SBIN_PATH

	# Initiallize polkit
	echo
        echo "Initializing polkit..."
        echo
        chroot $ROOT $SWL_POLKIT_INIT

	# Write version file
	echo $version > $SWL_VERSION_FILE
fi


####################################################################
# CLEANUP
####################################################################

### Remove temp dir ###
rm -rf $tmpdir


echo ""
echo "Base system installation complete."
