#!/bin/bash
###################################################################
#
# swl-list
#
# 
#
###################################################################


source $SWL_API_PATH/swl-api-functions


###################################################################
# USAGE
###################################################################
function usage
{
        cat << EOF

LIST USAGE:

swl-manager list (options) <list>

OPTIONS:
        -c	create blfs_root/scripts list
	-(f)d 	(force) download list
	-(f)i 	(force) install list
	-r	remove list
	-s	check installed and mirror status

EOF
}


####################################################################
# CONFIGURATION
####################################################################

#------------------------------------------------------------------#
# Parse command line
#------------------------------------------------------------------#

if [[ -z $1 ]]; then usage; exit; fi

blfs=false
download=false
force=false
install=false
list=$2
remove=false
stat=false


case $1 in

        -c)     blfs=true;;
        -d)     download=true;;
        -fd)    download=true; force=true;;
        -i)     install=true;;
        -fi)    install=true; force=true;;
        -r)     remove=true;;
        -s)     stat=true;;
        *)      usage ;;
esac


###################################################################
# LIST STATUS
###################################################################

if [[ $stat == true ]]; then
	if [[ -z $list ]]; then usage; exit 1; fi
	if [[ ! -f $list ]]; then echo "$list: file not found."; exit 1; fi
	list_check_status $list
fi


###################################################################
# CREATE LIST
###################################################################


### BLFS LIST ###
if [[ $blfs == true ]]; then
	list_create_blfs
fi


###################################################################
# DOWNLOAD LIST
###################################################################

if [[ $download == true ]]; then
	if [[ -z $list ]]; then usage; exit 1; fi
	if [[ ! -f $list ]]; then echo "$list: file not found."; exit 1; fi
	mirror_download_list $list $force
fi


###################################################################
# INSTALL LIST
###################################################################

if [[ $install == true ]]; then
	if [[ -z $list ]]; then usage; exit 1; fi
	if [[ ! -f $list ]]; then echo "$list: file not found."; exit 1; fi
	list_install $list $force
fi


###################################################################
# REMOVE LIST
###################################################################

if [[ $remove == true ]]; then
	if [[ -z $list ]]; then usage; exit 1; fi
	if [[ ! -f $list ]]; then echo "$list: file not found."; exit 1; fi
	list_remove $list
fi
