#!/bin/bash

grep bool Config.in  \
	| sed 's/.*\sbool\s//' \
	| sed 's/"//' \
	| sed 's/"//' \
	| sed 's/ /  /' \
	| sed 's/.*\sfor.*//' \
	| sed 's/.*\sDHCP.*//' \
	| sed 's/.*\swith.*//' \
	| sort





