#!/bin/bash

if [[ -z $1 ]]; then echo "no swl version"; exit; fi

ARCH=amd64
SWL=swl$1

#----------------------------------------------------------------------------#
for FILE in ./*.pkglog;
do
    echo Processing $FILE...

    # tar files
    pkg=${FILE%.pkglog}
    pkg=${pkg#./}
    tar_file="$pkg.tar"
    tar --no-recursion -cf $tar_file -T $FILE

    ### MAKE PACKAGE ###
    pkg="$pkg-$ARCH-$SWL.txz"
    mkdir extract
    cd extract

    tar -xf ../$tar_file

    makepkg -l y -c n ../$pkg
    cd ../
    mv -v $pkg ../packages/$pkg

    ### CLEANUP ###
    rm -rf extract
    rm $tar_file

done

exit
