#!/bin/bash

if [[ -z $1 ]]; then echo "no swl version"; exit; fi

echo "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>"
echo "<!DOCTYPE sublist SYSTEM \"/home/compnerd/blfs_root/packdesc.dtd\">"
echo "<sublist>"
echo "<name>Installed</name>"

for FILE in /var/lib/pkgtools/packages/*; do

	# get pkg and version
	pkg=${FILE##*/}
	pkg=${pkg%-amd64*}
	version=${pkg##*-}
	pkg=${pkg%-*}

	# lookup package
	lookup=$(grep -i "^$pkg  " /var/lib/swl/pkg-versions-$1.jhalfs)
	if [[ ! -z $lookup ]]; then
		pkg=${lookup%  *}
		version=${lookup#*  }
	fi

	# write xml
	echo "  <package>"
	echo "    <name>$pkg</name>"
	echo "    <version>$version</version>"
	echo "  </package>"


done

echo "</sublist>"
