#!/bin/bash


#----------------------------------------------------------------------------#
for FILE in /var/lib/iwlog/*;
do
    ### GET PACKAGE NAME AND VERSION ##
    echo Processing $FILE...

    ### CREATE FILTERED FILE ###
    filter_file=${FILE%.raw}
    filter_file_tmp="$filter_file.tmp"
    #echo $filter_file

    ### FILTER FILE ###
    TAB=$'\t'
    omit="${TAB}rename\|${TAB}symlink\|${TAB}unlink\|${TAB}access\|${TAB}utimes"
    grep -v "$omit" $FILE | cut -f3 | grep "^/" | sed 's#^//#/#g' > $filter_file_tmp
    cat $FILE | cut -f4 | grep "^/" | sed 's#^//#/#g' >> $filter_file_tmp
    echo "$(cat $filter_file_tmp | sort -u)" > $filter_file_tmp
    echo "$(grep -v "^/dev" $filter_file_tmp)" > $filter_file_tmp
    echo "$(grep -v "^/run" $filter_file_tmp)" > $filter_file_tmp
    echo "$(grep -v "^/proc" $filter_file_tmp)" > $filter_file_tmp
    echo "$(grep -v "^/sys" $filter_file_tmp)" > $filter_file_tmp
    echo "$(grep -v "^/sources" $filter_file_tmp)" > $filter_file_tmp

    ### CHECK EXISTS ###
    while IFS= read -r line; do 
        if [[ -f $line ]] || [[ -d $line ]]; then
	    echo $line >> $filter_file
	fi	    
    done < $filter_file_tmp

    ### CREATE TAR ###
    tar_file="$filter_file.tar"
    tar --no-recursion -cf $tar_file -T $filter_file

    ### MAKE PACKAGE ###
    package=${FILE%.iwlog.raw}
    package="$package-x86_64-swl01.txz"
    mkdir extract
    cd extract
    tar -xf $tar_file
    makepkg -l y -c n $package
    mv -v $package /var/lib/packages/
    cd ../

    ### CLEANUP ###
    rm -rf extract
    rm $filter_file
    rm $filter_file_tmp
    rm $tar_file

done

exit
