#!/bin/bash
####################################################################

SWL_VER_FILE=/var/lib/swl/swl-version
if [[ ! -f $SWL_VER_FILE ]]; then echo "No $SWL_VER_FILE."; exit 1; fi 
SWL_VER=$(cat $SWL_VER_FILE)
LFS_VER=$(echo "${SWL_VER:0:2}"."${SWL_VER:2:3}")

function install-blfs
{
	LFS_VER=$1
	
	# CLONE JHALFS
	pushd /sources
	rm -rf jhalfs
	git clone https://git.linuxfromscratch.org/jhalfs
	popd

	pushd /sources/jhalfs
	sed -i "s/COMMIT=\".*/COMMIT=\"$LFS_VER\"/"
	echo "q yes" | make
	popd
}

function gen-blfs-scripts
{
	PKG=$1

	pushd $HOME/blfs_root
	echo "q y" | make
	echo "CONFIG_$PKG=y" >> configuration
	./gen_pkg_book.sh
	popd
}

function make-scripts
{
	pushd $HOME/blfs_root
	$HOME/lfs/empty-scripts
	mkdir work
	pushd work
	../gen-makefile.sh
	make
	popd
	popd
}

### INSTALL CURRENT PACKAGE ###
rm /var/lib/jhalfs/BLFS/instpkg.xml
install-blfs $LFS_VER
gen-blfs-scripts $PKG
make-scripts

pushd $HOME/blfs_root
PKG_LIST=/tmp/$PKG.list
/usr/sbin/swl-manager list -c > /tmp/$PKG_LIST
sudo swl-manager list -d $PKG_LIST
sudo swl-manager list -i $PKG_LIST
build-instpkgxml $SWL_VER
rm $PKG_LIST
	
### BUILD NEW PACKAGE ###
install-blfs trunk
gen-blfs-scripts $PKG
/usr/src/slackwiig-lfs/scripts/build-versions > pkg-versions-trunk.jhalfs
sudo mv pkg-versions-trunk.jhalfs /var/lib/swl/
/usr/src/slackwiig-lfs/scripts/blfs-convert trunk
popd

