#!/bin/bash

for FILE in /var/lib/iwlog/*;
do
    ### GET PACKAGE NAME AND VERSION ##
    echo Processing $FILE...

    ### CREATE FILTERED FILE ###
    filter_file=${FILE%.raw}
    #echo $filter_file

    ### FILTER FILE ###
    TAB=$'\t'
    omit="${TAB}rename\|${TAB}symlink\|${TAB}unlink\|${TAB}access\|${TAB}utimes"
    echo "$(grep -v "$omit" $FILE)" | cut -f3 | sort -u > $filter_file
    echo "$(grep -v "/dev" $filter_file)" > $filter_file
    echo "$(grep -v "/sources" $filter_file)" > $filter_file
    echo "$(grep -v "/run" $filter_file)" > $filter_file
    echo "$(grep -v ".tmp" $filter_file)" > $filter_file
    echo "$(grep -v ".la" $filter_file)" > $filter_file

    ### CREATE TAR ###
    tar_file="$filter_file.tar"
    tar --no-recursion -cf $tar_file -T $filter_file

    ### MAKE PACKAGE ###
    package=${FILE%.iwlog.raw}
    package="$package-x86_64-slw01.txz"
    mkdir extract
    cd extract
    tar -xf $tar_file
    makepkg -l y -c n $package
    mv -v $package /var/lib/packages
    cd ../

    ### CLEANUP ###
    rm -rf extract
    rm $filter_file
    rm $tar_file

done


exit
