#!/bin/bash

echo
while IFS= read -r line;
do

	echo "============================================================="
	echo "Checking $line..."
	echo
	pkg=${line%-amd*}
	pkg=${pkg%-*}
	pkg="$pkg-"
	patched=$(grep "^$pkg" /var/lib/swl/lists/patches.list)
	if [[ ! -z $patched ]] ; then
		echo "PATCHED: $line -> $patched"
	fi
	echo
	found=$(find /var/lib/pkgtools/packages -name "$pkg*")
	if [[ ! -z $found ]]; then
		echo "FOUND: $found"
	fi


done < $1
