#!/bin/bash

# glibc
echo "/lib64/ld-linux-x86-64.so.2" >> /var/lib/swl/pkglog/glibc-2.39.pkglog
echo "/lib64/ld-lsb-x86-64.so.3" >> /var/lib/swl/pkglog/glibc-2.39.pkglog

# gcc
echo "/usr/bin/cc" >> /var/lib/swl/pkglog/gcc-13.2.0.pkglog

# bash
echo "/usr/bin/sh" >> /var/lib/swl/pkglog/bash-5.2.21.pkglog

# setuptools
echo "/usr/lib/python3.12/site-packages/setuptools/command/launcher manifest.xml" >> /var/lib/swl/pkglog/setuptools-69.1.0.pkglog
echo "/usr/lib/python3.12/site-packages/setuptools/script (dev).tmpl" >> /var/lib/swl/pkglog/setuptools-69.1.0.pkglog

# systemd
echo "/usr/lib/environment.d/99-environment.conf" >> /var/lib/swl/pkglog/systemd-255.pkglog
echo "/var/lib/hwclock" >> /var/lib/swl/pkglog/systemd-255.pkglog

# kernel
echo "/usr/lib/modules/6.7.4/build" >> /var/lib/swl/pkglog/kernel-6.7.4.pkglog


