#!/bin/bash
####################################################################
#
#
#
####################################################################

set +e

### ADD USER ###
SWL_USER=compnerd
useradd -m $SWL_USER
usermod -aG wheel $SWL_USER
passwd $SWL_USER

### SUDO ###
sed -i 's/%wheel ALL=(ALL) ALL/# %wheel ALL=(ALL) ALL/' /etc/sudoers.d/00-sudo
sed -i 's/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/' /etc/sudoers

### NETWORKING ###
cat << EOF > /etc/systemd/network/10-eth-static.network
[Match]
Name=ens3

[Network]
Address=192.168.122.69/24
Gateway=192.168.122.1
DNS=192.168.122.1
DNS=8.8.8.8
Domains=local
EOF

systemctl restart systemd-networkd

### MIRROR ###
cat << EOF > /etc/hosts
# Begin /etc/hosts

10.0.2.9 swl-build-122.local
::1       ip6-localhost ip6-loopback
ff02::1   ip6-allnodes
ff02::2   ip6-allrouters

192.168.69.239 swl-mirror

# End /etc/hosts
EOF

### CHANGE USER ###
su  - $SWL_USER << USER_EOF

### INSTALL SWL-MANAGER ###
pushd /usr/src
sudo git clone https://github.com/wiigelec/slackwiig-lfs
sudo chown -R $SWL_USER:$SWL_USER slackwiig-lfs
sudo ln -sv /usr/src/slackwiig-lfs/swl-manager/swl-manager /usr/sbin
sudo ln -sv /usr/src/slackwiig-lfs/swl-manager/swlm-config /usr/sbin
popd


### JHALFS ###
pushd /home/$SWL_USER
git clone https://git.linuxfromscratch.org/jhalfs
popd


### BLFS ###
pushd /home/$SWL_USER/jhalfs
cat << EOF > configuration
HAVE_NPROC=y
HAVE_CGROUP=y
BOOK_BLFS=y
BLFS_SYSD=y
INITSYS="systemd"
RUN_ME="./install-blfs-tools.sh auto"
BRANCH=y
COMMIT="12.2"
BLFS_ROOT="/blfs_root"
BLFS_XML="blfs-xml"
LFS_XML="lfs-xml"
LFS_BRANCH=y
BLFS_LFS_COMMIT="12.2"
TRACKING_DIR="/var/lib/jhalfs/BLFS"
EOF

# patch jhalfs

sudo mkdir /var/lib/jhalfs
sudo chown $SWL_USER:$SWL_USER /var/lib/jhalfs

echo "q y yes" | make
popd

### INIT BLFS ###
pushd /home/$SWL_USER/blfs_root
echo "q" | make
/usr/src/slackwiig-lfs/scripts/build-versions > pkg-versions-122.jhalfs
sudo mv pkg-versions-122.jhalfs /var/lib/swl
popd

### SWL DIRS ###
sudo mkdir -pv /var/lib/swl/{difflog,pkglog}
sudo rm -rf /var/lib/swl/packages/*

USER_EOF

### LOGOUT ###
exit
