#!/bin/bash

for FILE in /mnt/lfs/jhalfs/lfs-commands/chapter08/*;
do
    ### GET PACKAGE NAME AND VERSION ##
    echo Processing $FILE...

    package=${FILE##*\/}
    package=${package#*-}
    package=$(echo "$package" | tr '[:upper:]' '[:lower:]')
    #echo $package

    version=$(grep VERSION\= $FILE)
    version=${version/VERSION\=/}
    #echo $version

    ### INSTALLWATCH LOG FILE ###
    iwlog="$package"-"$version".iwlog.raw
    iwso="/usr/lib/installwatch.so"
    #echo $iwlog

    ### FIND PRELOAD LINE ###
    preload_line=0;
    preload_line=$(grep -n 'make.*install' $FILE)
    preload_line=${preload_line%%:*}
    if [[ "$preload_line" -eq 0 ]]; then
	preload_line=$(grep -n 'pip.*install' $FILE)
   	preload_line=${preload_line%%:*}
    fi
    if [[ "$preload_line" -eq 0 ]]; then
	preload_line=$(grep -n 'ninja.*install' $FILE)
   	preload_line=${preload_line%%:*}
    fi
    if [[ "$preload_line" -eq 0 ]]; then
	preload_line=$(grep -n '# Start of LFS book script' $FILE)
   	preload_line=${preload_line%%:*}
    fi
    #echo $preload_line

    ### FIND LAST LINE ###
    last_line=0
    last_line=$(grep -n '# End of LFS book script' $FILE)
    last_line=${last_line%%:*}

    ### PROCESS FILE ###
    outfile="$FILE".tmp
    declare -i linenum=1
    while IFS= read -r line;
    do
        if (( linenum == preload_line )); then
            echo "export INSTALLWATCHFILE=$iwlog" >> $outfile
            echo "export LD_PRELOAD=$iwso" >> $outfile
        fi
        if (( linenum == last_line )); then
            echo "unset INSTALLWATCHFILE" >> $outfile
            echo "unset LD_PRELOAD" >> $outfile
        fi
	#echo "$line"
        echo "$line" >> $outfile
        linenum+=1

    done < $FILE

    ### RENAME FILES ###
    chmod a-x $FILE
    mv $FILE $FILE.org
    mv $outfile $FILE
    chmod a+x $FILE

done


exit
