#!/bin/bash

for FILE in ./*; do

	pkg=${FILE#\./}
	pkg=${pkg%-amd64*}
	version=${pkg##*-}
	pkg=${pkg%-*}
	pkg_vers="$pkg  $version"
	found=
	if [[ -z $(grep "$pkg_vers" /var/lib/swl/swl-versions.121) ]]; then
	
		found=$(grep "^$pkg  " /var/lib/swl/swl-versions.121)
		if [[ -z $found  ]]; then
			found="NOT*FOUND"
		fi
	fi
	echo "$pkg_vers $found"
done
