#!/bin/bash

#-----------------------------------------------------------------------------#
#
# swl-deps
# Dependency manager for slackwiig-lfs
#
#-----------------------------------------------------------------------------#

### CONFIGURATION ###
SCRIPT_DIR="$HOME/blfs_root/scripts/"
INSTALL_DIR="/var/lib/pkgtools/packages/"
PKG_DIR="/var/lib/swl/packages/"
LIST_DIR="/var/lib/swl/lists/"
MIRROR="http://localhost:8000/swl-packages.121/"

#-----------------------------------------------------------------------------#
function createList ( )
{
	if [[ -z "$location" ]]; then
		location=$SCRIPT_DIR
	fi

	for FILE in $location/*;
	do
		pkg=${FILE#*-z-}
		pkg=$(echo $pkg | tr '[:upper:]' '[:lower:]')
		found=$(grep ^$pkg $LIST_DIR/swl-packages-121.list | head -n1)
		if [[ -z $found ]]; then
			found="NOT FOUND: $pkg"
		fi
		echo "$found"
	done

}

#-----------------------------------------------------------------------------#
function browseLists ( )
{
	if [[ ! -e $LIST_DIR ]]; then
		echo "LIST_DIR $LIST_DIR does not exist."
		return
	fi

	lynx ${MIRROR}lists/

}

#-----------------------------------------------------------------------------#
function installStatus ( )
{
	if [[ -z "$list" ]]; then 
		echo "No list specified" 
		exit
	fi

	# read file
    	while IFS= read -r line;
    	do
		local out_line=""
		# check installed
		out_line=$(check_installed $line)
		if [[ ! -z $out_line ]]; then
			echo "$line  INSTALLED"
			continue
		fi

		# check file
		out_line=$(check_file $line)
		if [[ ! -z $out_line ]]; then
			echo "$line  $out_line"
			continue
		fi

		# check mirror
		out_line=$(check_mirror $line)
		if [[ ! -z $out_line ]]; then
			echo "$line  $out_line"
			continue
		fi

		out_line="NOT FOUND"
		
		echo "$line  $out_line"

    	done < $list

}
    	
#-----------------------------------------------------------------------------#
function removeStatus ( )
{
	if [[ -z "$list" ]]; then 
		echo "No list specified" 
		exit
	fi

	# read file
        while IFS= read -r line;
        do
		# check used
		used=$(check_used $line)
		if [[ ! -z $used ]]; then
			echo "$line  USED"
		else
			echo "$line"
		fi
		
	done < $list
}

#-----------------------------------------------------------------------------#
function downloadDeps ( )
{
	if [[ -z "$list" ]]; then 
		echo "No list specified" 
		exit
	fi
	
	# read list
    	while IFS= read -r line;
    	do
		# check mirror
		local url=$(check_mirror $line)
		if [[ -z $url ]]; then
			echo "SKIPPING $line: NOT FOUND ON MIRROR"
			continue
		fi

		# download
		wget -nc -P $PKG_DIR $url

    	done < $list
}

#-----------------------------------------------------------------------------#
function installDeps ( )
{
	if [[ -z "$list" ]]; then 
		echo "No list specified" 
		exit
	fi
	if [[ -z "$install_cmd" ]]; then 
		echo "No install command specified" 
		exit
	fi

	# read list
	local error=0
        while IFS= read -r line;
        do
		local pkg_file=$(check_installed $line)
		if [[ ! -z $pkg_file && $force == 0 ]]; then
			echo "SKIPPING: $line INSTALLED"
			continue
		fi
                pkg_file=$(check_file $line)
                if [[ -z $pkg_file ]]; then
                        echo "ERROR: $line NOT FOUND"
                        break
                fi

		# install pkg
		$install_cmd $pkg_file
		error=$?
		
        done < $list

	if [[ $error = 0 ]]; then
		cp -i $list $LIST_DIR
	fi

}

#-----------------------------------------------------------------------------#
function removeDeps ( )
{
        if [[ -z "$list" ]]; then
                echo "No list specified"
                exit
        fi
        if [[ -z "$install_cmd" ]]; then
                echo "No remove command specified"
                exit
        fi

        # read list
	local error=0
        while IFS= read -r line;
        do
                local used=$(check_used $line)
                if [[ ! -z $used ]]; then
                        echo "SKIPPING: $line USED"
                        continue
                fi

                # remove pkg
                $remove_cmd $line
		error=$?

        done < $list

	if [[ $error = 0 ]]; then
		rm -i ${list}
	fi

}

#-----------------------------------------------------------------------------#
function check_installed ( )
{
	pkg=$1
	pkg=${pkg%.txz}
	local output=""
	if [[ $(find "$INSTALL_DIR/" -name $pkg) ]]; then
		output="$INSTALL_DIR/$pkg"
	fi

	echo $output
}

#-----------------------------------------------------------------------------#
function check_file ( )
{
	pkg=$1
	local output=""
	if [[ $(find "$PKG_DIR/" -maxdepth 1 -name $pkg) ]]; then
		output="$PKG_DIR/$pkg"
	fi

	echo $output
}

#-----------------------------------------------------------------------------#
function check_mirror ( )
{
	pkg=$1
	local output=""
	local url=${MIRROR}packages
	if [[ "$list" == *"lfs-base.list" ]]; then
	       url="$url/lfs-base/$pkg"
        else
		dir=${pkg:0:1}
		url="$url/$dir/$pkg"
	fi

        wget -q --spider $url
	if [[ $? -eq 0 ]]; then
		output=$url
	fi

	echo $output
}

#-----------------------------------------------------------------------------#
function check_used ( )
{
	pkg=$1
	echo "$(grep --exclude=$list $pkg $LIST_DIR*)"
}

#-----------------------------------------------------------------------------#
function usage ( )
{
	echo "-c | --create"
	echo "-b | --browse"
	echo "-s | --status"
	echo "-d | --download"
	echo "-i | --install"
	echo "-f | --force-install"
	echo "-u | --remove-status"
	echo "-r | --remove"
	exit
}

###############################################################################
### MAIN ###

# parse command line
action=$1
list=$2
install_cmd=$3
remove_cmd=$3
force=0


case $action in
    -c|--create )
        createList
        ;;
    -b|--browse )
        browseLists
        ;;
    -s|--install-status )
	installStatus
        ;;
    -d|--download )
    	downloadDeps
        ;;
    -i|--install )
    	installDeps
        ;;
    -f|--force-install )
	force=1
    	installDeps
        ;;
    -u|--remove-status )
    	removeStatus
        ;;
    -r|--remove )
    	removeDeps
        ;;
    * ) usage ;;
esac

###############################################################################


